[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.31.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-pc-windows-msvc"]
# Extra runtime files (DLLs, GStreamer plugins, assets) to bundle alongside the binary
include = [
  "runtime/assets",
  "runtime/lib",
  "runtime/ffi-7.dll",
  "runtime/ffmpeg.exe",
  "runtime/gio-2.0-0.dll",
  "runtime/glib-2.0-0.dll",
  "runtime/gmodule-2.0-0.dll",
  "runtime/gobject-2.0-0.dll",
  "runtime/gstapp-1.0-0.dll",
  "runtime/gstaudio-1.0-0.dll",
  "runtime/gstbase-1.0-0.dll",
  "runtime/gstcodecparsers-1.0-0.dll",
  "runtime/gstcodecs-1.0-0.dll",
  "runtime/gstcuda-1.0-0.dll",
  "runtime/gstd3d11-1.0-0.dll",
  "runtime/gstd3d12-1.0-0.dll",
  "runtime/gstd3dshader-1.0-0.dll",
  "runtime/gstdxva-1.0-0.dll",
  "runtime/gstgl-1.0-0.dll",
  "runtime/gstpbutils-1.0-0.dll",
  "runtime/gstreamer-1.0-0.dll",
  "runtime/gsttag-1.0-0.dll",
  "runtime/gstvideo-1.0-0.dll",
  "runtime/intl-8.dll",
  "runtime/libmpv-2.dll",
  "runtime/orc-0.4-0.dll",
  "runtime/pcre2-8-0.dll",
  "runtime/sqlite3-0.dll",
  "runtime/x264-164.dll",
  "runtime/z-1.dll",
]
