//! Catalog of popular games used to resolve a game title to store metadata
//! (currently a Steam appid) without a network round-trip.
//!
//! Today this is backed solely by a bundled snapshot of the top ~500 Steam
//! titles, but it's named provider-agnostically: non-Steam sources (e.g. other
//! storefronts/metadata APIs) are expected to feed into the same lookup later.
//!
//! Matching a window/source title to an appid previously hit Steam's
//! `storesearch` HTTP endpoint on every lookup (slow, network-dependent, and it
//! just trusted the first result). For the common case — a popular game — we can
//! answer instantly and offline from the bundled snapshot. Only a miss falls
//! back to the network search (see `utils::resolve_steam_app_id`).
//!
//! Storage is "bundle + refresh": a static snapshot is compiled into the binary
//! (`assets/steam_top500.json`) so the very first launch already has data, and
//! [`refresh_if_stale`] periodically rewrites a cache copy from SteamSpy so the
//! list doesn't go stale between releases. The cache, when present, takes
//! precedence over the bundled snapshot at load time.

use std::collections::HashMap;
use std::sync::OnceLock;
use std::time::Duration;

use serde::{Deserialize, Serialize};

/// Compiled-in snapshot, generated by `scripts/fetch-steam-top500.ps1`.
const BUNDLED: &str = include_str!("../assets/steam_top500.json");

/// How long a refreshed cache is considered fresh before we re-fetch.
const REFRESH_INTERVAL: Duration = Duration::from_secs(7 * 24 * 60 * 60);

#[derive(Deserialize, Serialize, Clone)]
pub struct CatalogEntry {
    pub appid: u32,
    pub name: String,
}

struct Catalog {
    /// Normalized name -> appid.
    by_name: HashMap<String, u32>,
}

static CATALOG: OnceLock<Catalog> = OnceLock::new();

fn cache_path() -> std::path::PathBuf {
    crate::utils::get_storage_root()
        .join("Cache")
        .join("steam_top500.json")
}

/// Collapse a title to a comparison key: lowercase, keep only alphanumerics.
/// This drops spaces, punctuation, trademark glyphs, and the zero-width
/// characters some window titles carry (e.g. the mangled "A\u{200b}RC Raiders"),
/// so "ARC Raiders", "arc raiders", and the junk-laden variant all collapse to
/// `arcraiders`.
fn normalize(title: &str) -> String {
    title
        .chars()
        .flat_map(|c| c.to_lowercase())
        .filter(|c| c.is_alphanumeric())
        .collect()
}

fn parse(raw: &str) -> Option<Vec<CatalogEntry>> {
    serde_json::from_str::<Vec<CatalogEntry>>(raw).ok().filter(|v| !v.is_empty())
}

fn load() -> Catalog {
    // Prefer the runtime cache (fresher), fall back to the bundled snapshot.
    let ordered = std::fs::read_to_string(cache_path())
        .ok()
        .and_then(|s| parse(&s))
        .or_else(|| parse(BUNDLED))
        .unwrap_or_default();

    let mut by_name = HashMap::with_capacity(ordered.len());
    for entry in &ordered {
        // First (higher-ranked) entry wins on a normalized-name collision.
        by_name.entry(normalize(&entry.name)).or_insert(entry.appid);
    }
    Catalog { by_name }
}

/// Resolve a game title to a Steam appid from the bundled/cached catalog, or
/// `None` if it isn't a known popular title (caller should fall back to search).
pub fn lookup_appid(title: &str) -> Option<u32> {
    let key = normalize(title);
    if key.is_empty() {
        return None;
    }
    CATALOG.get_or_init(load).by_name.get(&key).copied()
}

/// Refresh the cached catalog from SteamSpy if the cache is missing or older
/// than [`REFRESH_INTERVAL`]. Blocking; call from a background thread. The
/// refreshed list is picked up on the next launch (the in-memory catalog is
/// loaded once), which is fine for a slowly-changing popularity list.
pub fn refresh_if_stale() {
    let path = cache_path();
    if let Ok(modified) = path.metadata().and_then(|m| m.modified()) {
        if modified.elapsed().map(|age| age < REFRESH_INTERVAL).unwrap_or(false) {
            return;
        }
    }

    let client = match reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(30))
        .user_agent("Rekaptr/1.0")
        .build()
    {
        Ok(c) => c,
        Err(_) => return,
    };

    // `all&page=0` is SteamSpy's top 1000 by owners.
    let json: serde_json::Value = match client
        .get("https://steamspy.com/api.php?request=all&page=0")
        .send()
        .and_then(|r| r.json())
    {
        Ok(j) => j,
        Err(e) => {
            log::warn!("[GameCatalog] refresh failed: {}", e);
            return;
        }
    };

    let Some(obj) = json.as_object() else { return };
    let mut ranked: Vec<(i64, CatalogEntry)> = obj
        .values()
        .filter_map(|v| {
            let appid = v.get("appid")?.as_u64()? as u32;
            let name = v.get("name")?.as_str()?.trim().to_string();
            if name.is_empty() {
                return None;
            }
            // owners looks like "100,000,000 .. 200,000,000"; rank by lower bound.
            let lower = v
                .get("owners")
                .and_then(|o| o.as_str())
                .and_then(|s| s.split("..").next())
                .map(|s| s.chars().filter(|c| c.is_ascii_digit()).collect::<String>())
                .and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(0);
            Some((lower, CatalogEntry { appid, name }))
        })
        .collect();

    ranked.sort_by(|a, b| b.0.cmp(&a.0));
    let top: Vec<CatalogEntry> = ranked.into_iter().take(500).map(|(_, e)| e).collect();
    if top.is_empty() {
        return;
    }

    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Ok(s) = serde_json::to_string(&top) {
        if std::fs::write(&path, s).is_ok() {
            log::info!("[GameCatalog] refreshed top-{} catalog from SteamSpy", top.len());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_snapshot_parses() {
        let entries = parse(BUNDLED).expect("bundled snapshot must be valid JSON");
        assert!(entries.len() >= 400, "expected ~500 entries, got {}", entries.len());
    }

    #[test]
    fn normalize_collapses_punctuation_case_and_zero_width() {
        assert_eq!(normalize("Counter-Strike: Global Offensive"), "counterstrikeglobaloffensive");
        // Zero-width chars, trademark glyph, and casing all collapse away.
        assert_eq!(normalize("A\u{200b}RC  Raiders\u{2122}"), "arcraiders");
        assert_eq!(normalize("   "), "");
    }

    #[test]
    fn known_title_maps_to_expected_appid() {
        let entries = parse(BUNDLED).unwrap();
        let by_name: HashMap<String, u32> =
            entries.iter().map(|e| (normalize(&e.name), e.appid)).collect();
        assert_eq!(by_name.get(&normalize("Counter-Strike: Global Offensive")).copied(), Some(730));
    }
}
